name: 'Setup Preview Env'
description: 'Sets preview password env var with fallback and optionally validates deploy token'
inputs:
  set-password:
    description: 'Whether to export VITE_PREVIEW_PASSWORD'
    required: false
    default: 'true'
  validate-token:
    description: 'Whether to fail if AZURE_STATIC_WEB_APPS_API_TOKEN is missing'
    required: false
    default: 'false'
outputs: {}
runs:
  using: 'composite'
  steps:
    - name: Export Preview Password (Fallback)
      if: inputs.set-password == 'true'
      shell: bash
      run: |
        if [ -z "${{ secrets.VITE_PREVIEW_PASSWORD }}" ]; then
          echo "VITE_PREVIEW_PASSWORD=haslam" >> $GITHUB_ENV
        else
          echo "VITE_PREVIEW_PASSWORD=${{ secrets.VITE_PREVIEW_PASSWORD }}" >> $GITHUB_ENV
        fi
    - name: Validate Deploy Token
      if: inputs.validate-token == 'true'
      shell: bash
      run: |
        if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
          echo 'ERROR: Missing AZURE_STATIC_WEB_APPS_API_TOKEN secret.' >&2
          exit 1
        fi
        echo 'Deployment token present.'
